### ISSUE TITLE
Query on Model Release

### ISSUE THREAD

**Issue by Luo-Yihang** [adobe-research/SuperGaussian#2]
Thank you for the great work! I was wondering if there are any plans to release the finetuned VideoGigaGAN model?

**Comment by yshen47** [comment]
Thanks for your follow up, Yihang! Unfortunately, VideoGigaGAN is not ready to release at this moment, since it is the work of another cool team at Adobe. The good thing is that we prepare the output of the finetuned videogigagan at each stage on our test set of MVImgNet, so people can still potentially make comparison.

**Comment by yshen47** [comment]
Btw, upscale-a-video is a good alternative to Videogigagan, which is also one generative video upsampler. It seems they release codebase and checkpoints last months, https://github.com/sczhou/Upscale-A-Video.
